---
- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - gcc
    - epel-release
    - python36-devel
    - libsqlite3-devel
    - openssl-devel
    - bzip2-devel
    - libffi-devel
  become: yes

- name: Install pip
  yum: 
    name: python-pip

- name: Update pip and setuptools
  shell: "pip install --upgrade pip && pip install --upgrade setuptools"
