---
- name: ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - gcc
    - epel-release
    - python36-devel
    - openssl-devel
    - bzip2-devel
    - libffi-devel
  become: yes
